config/routes.rb
DevRuby::Application.routes.draw do
  root :to => "home#index"
  match "/activities" => "home#activities", :as => :activities
  match "/about" => "home#about", :as => :about
  match "/rss" => "home#rss", :as => :rss

  resources :sessions, :only => [:create, :destroy]
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout  
  match "/restricted" => "sessions#login_required", :as => :login_required

  resources :posts do
    resources :translations, :only => [:index, :new, :create]
    resource :translation_request, :only => [:create, :destroy]
  end

  resources :topics, :only => [:edit, :update]

  resources :users, :only => [:show, :new, :create]

end

app/models/post.rb
class Post < ActiveRecord::Base
  # Associations
  has_many :translations

  has_many :translation_requests
  has_many :users, :through => :translation_requests

  has_one :topic

  # Note: you may think 'alias requesting_users users' is better, but
  # it spoils eager loading (see also: posts#index)
  def requesting_users
    self.translation_requests.map &:user
  end

  # Plugins
  has_friendly_id :number

  has_ancestry
  alias root? is_root?

  # Validations
  validates :number, presence: true, uniqueness: true
  validates :subject, presence: true
  validates :from, presence: true
  validates :time, presence: true
  validates :body, presence: true

  # Callbacks
  
  after_save :update_topic

  def update_topic
    if self.root?
      topic = Topic.new
      topic.post_id = self.id
      topic.subject = self.subject
      topic.last_update = self.time

      raise "failed to create topic" unless topic.save
    else
      topic = Topic.find_by_post_id(self.root.id)
      if topic.last_update < self.time
        topic.last_update = self.time
        topic.save
      else
        puts "warning: this mail (#{self.inspect}) is older than last_update" 
      end
    end
  end

  # scopes
  
  scope :no_duplicates, lambda {
    group(column_names.map{|name| "#{table_name}.#{name}" }.join(', '))
  }
  
  scope :translated, lambda{
    joins(:translations).
    no_duplicates
  }

  scope :not_translated, lambda{
    where('(SELECT COUNT(*) FROM translations WHERE post_id = posts.id) = 0')
  }

  scope :has_request, lambda{
    joins(:translation_requests).
    no_duplicates
  }

  scope :recent_requested, lambda{
    has_request.
    order('(SELECT MAX(created_at) FROM "translation_requests"
            WHERE post_id = posts.id) DESC').
    includes(:translations, {translation_requests: :user})
  }

  scope :top_requested, lambda{
    has_request.
    not_translated.
    order('(SELECT COUNT(*) FROM "translation_requests"
            WHERE post_id = posts.id) DESC').
    includes(:translations, {translation_requests: :user})
  }

  scope :recent_translated, lambda{
    translated.
    order('(SELECT MAX(created_at) FROM "translations"
            WHERE post_id = posts.id) DESC').
    includes(:translations, {translation_requests: :user})
  }

  # Instance methods

  def created_at
    self.time
  end

  def to_s
    self.number.to_s
  end

  def translation
    if (trs = self.translations)
      trs.max_by{|tr| tr.created_at}
    end
  end
  alias last_translation translation
  alias translated? translation

  def topic_subject
    self.root.topic.subject
  end

  def translated_body
    translation ? translation.body : body
  end

  def css_class
    if self.translated? 
      "translated" 
    else
      "not_translated"
    end
  end

  REXP_FROM = /(.*) <(.*)>/
  def from_name
    self.from[REXP_FROM, 1]
  end

  def from_address
    self.from[REXP_FROM, 2]
  end
end

app/controllers/posts_controller.rb
require 'blade.rb'

class PostsController < ApplicationController
  before_filter :find_post, :only => [:show]

  # GET /posts
  def index
    case params[:view]
    when "recent_requested"
      @posts = Post.recent_requested.paginate(page: params[:page],
                                              per_page: 20)
      @title = "Recently requested"
    when "top_requested"
      @posts = Post.top_requested.paginate(page: params[:page],
                                           per_page: 20)
      @title = "Top requested"
    when "recent_translated"
      @posts = Post.recent_translated.paginate(page: params[:page],
                                               per_page: 20)
      @title = "Recent translated"
    when "search"
      search = Post.search(params[:search]).order("number DESC")
      @posts = search.paginate(page: params[:page], per_page: 20)
      @title = "Search result"
    else
      @title = "Recent posts"
      @topics = Topic.includes(:root).
        paginate(page: params[:page],
                 per_page: 25,
                 order: "last_update DESC")
      @posts = @topics.map{|topic|
          tree = topic.root.subtree.includes(:translations, {translation_requests: :user}).arrange
          [tree.keys.first, tree]
      }
    end
  end

  # GET /posts/1
  def show
    if @post.root?
      @root = @post

      respond_to do |format|
        format.html # show.html.erb
      end
    else
      redirect_to :action => :show, :id => @post.root.number, :anchor => @post.number
    end
  end

  # GET /posts/new
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /posts
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def format_posts(tree, &block)
    return "" if tree.empty?

    concat "<ul>".html_safe
    tree.each{|parent, children|
      concat "<li>".html_safe
      yield parent
      format_posts(children, &block)
      concat "</li>".html_safe
    }
    concat "</ul>".html_safe
  end

  def format_subject(s, opts={})
    if s =~ /\A(\[.*\])(.*)/
      tags = " <span class='redmine_tags'> - #{h $1}</span>"
      "#{h $2.lstrip}#{tags unless opts[:no_tags]}".html_safe
    else
      s
    end
  end
end

app/views/posts/_post.html.slim
// Renders post information in a line like:
//
//   43603 : (title here if with_title) Usaku NAKAMURA <redmine ruby-lang.org> @ 2011-05-31 16:43:08 +0900 (stars here)
//

.post_link
  div class="#{post.css_class}"
    a href="#{post_path(post)}"
      span.number
        = post.number
      '  :

      - if with_title
        span.title
          = format_subject(post.root.topic.subject, no_tags: true)
          '  /
        
      span.from
        = post.from

      - if not with_title
        '  @
        span.time
          = post.time

    '

    // Existing stars

    - post.requesting_users.each do |user|
      - next if user == current_user
      span.black_star title="#{user.name}"
        = link_to black_star, user_path(user)

    // Star button

    - if current_user 
      - if current_user.requesting?(post)
        span.black_star
          = link_to black_star, post_translation_request_path(post), method: "delete", remote: true, id: "star_#{post.number}"
      - else
        span.white_star
          = link_to white_star, post_translation_request_path(post), method: "post", remote: true, id: "star_#{post.number}"
    - else
      span.white_star
        = link_to white_star, login_required_path(path: request.path)

app/views/posts/_posts_thread.html.slim
- posts = [root] + root.descendants.includes(:translations)

- posts.each do |post|
  .post.clearfix
    a name="#{post.number}"
    h3
      span.post_number
        = link_to post.number, post_path(root, anchor: post.number)
      '
      span.post_from 
        = link_to post.from_name, posts_path(:view => "search", :'search[from_contains]' => post.from_name)
        |  &lt;
        = post.from_address
        | &gt;
      '
      span.post_time
        = "(#{post.time})"
      '
      span.post_subject
        = post.subject

    .left
      - if (tr = post.translation)
        pre = format_body(tr.body)
        = link_to 'Refine translation', new_post_translation_path(post.number)
        - if post.translations.size >= 2
          = " / "
          = link_to "View logs (#{post.translations.size})", post_translations_path(post.number)

      - else
        pre 
          | [Translation not available]
        = link_to 'Add translation', new_post_translation_path(post.number)

    .right
      pre = format_body(post.body)

app/views/posts/_posts_tree.html.slim
// Renders a tree of posts like:
//
// - fix stateless-iso-2022-jp - [Backport92 - Backport #4348]
//   - 43600 : Yuki Sonoda <yugui yugui.jp> @ 2011-05-31 11:31:23 +0900 (star)
//   - 43602 : Yuki Sonoda <yugui yugui.jp> @ 2011-05-31 13:47:06 +0900 (star)
//

.post_index
  - @posts.each do |root, tree|
    ul.post_tree
      li
        div class="root #{root.css_class}"
          = link_to format_subject(root.topic.subject), root

          - if signed_in? and root.topic.needs_subject_translation?
            '
            a.edit_subject href="#{edit_topic_path(root.topic)}"
              | (edit)

        - format_posts(tree) do |post|
          = render post, with_title: false

app/views/posts/index.html.slim
h2 = @title

- if params[:view] 

  ul
    - @posts.each do |post|
      li 
        = render post, with_title: true

  .pagination
    = will_paginate @posts

  - if params[:view] == "top_requested" and @posts.empty?
    p
      ' Currently, all
      = link_to "requested posts", posts_path(view: "recent_requested")
      '  have already been translated :-)

- else
  = render "posts_tree", posts: @posts

  .pagination
    = will_paginate @topics

app/views/posts/show.html.slim
h2
  = @root.topic.subject
  - if signed_in?
    '
    a.edit_subject href="#{edit_topic_path(@root.topic)}"
      | (edit subject)

= render "posts_thread", root: @root

div
  = link_to 'Back', posts_path