config/routes.rb
DevRuby::Application.routes.draw do
  root :to => "home#index"
  match "/activities" => "home#activities", :as => :activities
  match "/about" => "home#about", :as => :about
  match "/rss" => "home#rss", :as => :rss

  resources :sessions, :only => [:create, :destroy]
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout  
  match "/restricted" => "sessions#login_required", :as => :login_required

  resources :posts do
    resources :translations, :only => [:index, :new, :create]
    resource :translation_request, :only => [:create, :destroy]
  end

  resources :topics, :only => [:edit, :update]

  resources :users, :only => [:show, :new, :create]

end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title ruby-dev translation (beta)
    = stylesheet_link_tag :all
    = javascript_include_tag "jquery", "jquery_ujs"
    = csrf_meta_tag

    link rel="alternate" type="application/rss+xml" title="RSS (for readers)" href="#{rss_path(view: 'reader')}"
    link rel="alternate" type="application/rss+xml" title="RSS (for translators)" href="#{rss_path(view: 'translator')}"

    // Google analytics
    | <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-2023947-3']);
      _gaq.push(['_trackPageview']);

      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();
      </script>

    // CSS and javascript for hiding redmine's ticket description
    // see also: application_helper
    | <style> .redmine_desc{ display: none; }</style>
      <script>
        $(function(){
          var descs = $.makeArray($(".redmine_desc"));
          // show the desc of the first mail of the thread
          $(descs[0]).show();

          $(".redmine_desc_bar").each(function(i, elem){
            $(elem).click(function(){
              $(descs[i]).toggle();
              return false;
            });
          });
        });
      </script>

  body
    // Header
    #header
      #user_nav
        - if current_user
          ' Welcome, 
          = link_to current_user.name, current_user
          ' !
          = link_to "Sign Out", signout_path
        - else
          = link_to "Sign in with Twitter", "/auth/twitter"

      h1 = link_to "ruby-dev translation (beta)", root_path

    // Menu
    ul#menu.clearfix
      li = link_to "About", about_path
      li = link_to "Recent posts", posts_path
      li = link_to "Recently translated", posts_path(view: :recent_translated)
      li = link_to "Top requested", posts_path(view: :top_requested)
      - if signed_in?
        li = link_to "Recently requested", posts_path(view: :recent_requested)
        li = link_to "Your activities", activities_path
      li = link_to "RSS", rss_path
      li.search
        = form_for Post.search(params[:search]) do |f|
          = hidden_field_tag :view, "search"
          = f.text_field :topic_subject_or_translations_body_contains
          = submit_tag "Search"

    // Content
    #content
      - if flash[:error] or flash[:notice]
        #flash
          #error = flash[:error]
          #notice = flash[:notice]

      = yield

    // Footer
    #footer
      div
        | ruby-dev translation
      div
        a href="http://github.com/yhara/dev-ruby/"
          | source(github)
        = " / "
        a href="http://github.com/yhara/dev-ruby/issues"
          | issues